services:
  db:
    container_name: cardgame-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: cardgame
    image: mariadb:11.6.2
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql

  backend:
    command: > 
      java -jar /app/backend-0.0.1-SNAPSHOT.jar
    container_name: cardgame-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/cardgame
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
    image: amazoncorretto:17
    ports:
      - "8080:8080"
    volumes:
      - ./backend/build/libs:/app

  frontend:
    container_name: cardgame-frontend
    depends_on:
      - backend
    image: nginx:1.26
    ports:
      - "4200:80"
    volumes:
      - ./frontend/dist/frontend/browser:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  default:
    driver: bridge

volumes:
  mariadb:
    name: cardgame-mariadb
